import React from 'react';
import { View } from 'react-native';
import { useTheme } from '../theme';
import { Icon } from './Icon';
import { Text } from './Text';

/**
 * TEMPORARY — test bots.
 *
 * Marks content generated by the test bots so nobody mistakes a bot bid or a
 * bot job for a real one. Rendered inline (unlike UpdateBanner, which floats
 * absolutely) so it pushes content down instead of covering a header, and so
 * it scrolls away with whatever it labels.
 *
 * Remove this file, its export in index.ts, and its call sites together with
 * the backend's app/Bots.
 */
export function TestBanner({
  message = 'Conteúdo de teste gerado automaticamente por um bot.',
}: {
  message?: string;
}) {
  const t = useTheme();

  return (
    <View
      style={{
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: t.colors.dangerSoft,
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginBottom: 12,
      }}
      accessibilityRole="alert"
    >
      <Icon name="flash" size={18} color={t.colors.danger} />
      <Text weight="700" color={t.colors.danger} style={{ flex: 1, fontSize: 13 }}>
        {message}
      </Text>
    </View>
  );
}

/** Inline pill for list rows, where a full banner per item would be noise. */
export function TestBadge({ label = 'TESTE' }: { label?: string }) {
  const t = useTheme();

  return (
    <View
      style={{
        backgroundColor: t.colors.dangerSoft,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 999,
        alignSelf: 'flex-start',
      }}
    >
      <Text variant="caption" weight="800" color={t.colors.danger} style={{ fontSize: 11 }}>
        {label}
      </Text>
    </View>
  );
}
